# Generated by Django 3.2.16 on 2024-03-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='rate',
            field=models.FloatField(verbose_name='Курс валюты в рублях'),
        ),
    ]
